//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace api_model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB_EMBUARAMAEntities : DbContext
    {
        public DB_EMBUARAMAEntities()
            : base("name=DB_EMBUARAMAEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TB_BRASSAGEM> TB_BRASSAGEM { get; set; }
        public virtual DbSet<TB_BRASSAGEM_MOAGEM> TB_BRASSAGEM_MOAGEM { get; set; }
        public virtual DbSet<TB_CALDEIRA> TB_CALDEIRA { get; set; }
        public virtual DbSet<TB_CLARIFICACAO> TB_CLARIFICACAO { get; set; }
        public virtual DbSet<TB_EMPRESA> TB_EMPRESA { get; set; }
        public virtual DbSet<TB_LUPULO> TB_LUPULO { get; set; }
        public virtual DbSet<TB_MOAGEM> TB_MOAGEM { get; set; }
        public virtual DbSet<TB_MOSTO_PRIMARIO> TB_MOSTO_PRIMARIO { get; set; }
        public virtual DbSet<TB_PREPARO_AGUA> TB_PREPARO_AGUA { get; set; }
        public virtual DbSet<TB_REGISTRO_LAVAGEM> TB_REGISTRO_LAVAGEM { get; set; }
        public virtual DbSet<TB_RENDIMENTO_MOSTURA> TB_RENDIMENTO_MOSTURA { get; set; }
        public virtual DbSet<TB_REPOUSO> TB_REPOUSO { get; set; }
        public virtual DbSet<TB_SACARIFICACAO> TB_SACARIFICACAO { get; set; }
        public virtual DbSet<TB_TIPO_CERVEJA> TB_TIPO_CERVEJA { get; set; }
        public virtual DbSet<TB_TIPO_LUPULO> TB_TIPO_LUPULO { get; set; }
        public virtual DbSet<TB_TIPO_MALTE> TB_TIPO_MALTE { get; set; }
        public virtual DbSet<TB_TIPO_REPOUSO> TB_TIPO_REPOUSO { get; set; }
        public virtual DbSet<TB_USUARIO> TB_USUARIO { get; set; }
    }
}
