//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace api_model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_BRASSAGEM_MOAGEM
    {
        public int ID_BRASSAGEM_MOAGEM { get; set; }
        public int ID_MOAGEM { get; set; }
        public int ID_BRASSAGEM { get; set; }
    
        public virtual TB_BRASSAGEM TB_BRASSAGEM { get; set; }
        public virtual TB_MOAGEM TB_MOAGEM { get; set; }
    }
}
