//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace api_model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_BRASSAGEM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_BRASSAGEM()
        {
            this.TB_BRASSAGEM_MOAGEM = new HashSet<TB_BRASSAGEM_MOAGEM>();
            this.TB_REGISTRO_LAVAGEM = new HashSet<TB_REGISTRO_LAVAGEM>();
        }
    
        public int ID_BRASSAGEM { get; set; }
        public string ID_LOTE_PRODUCAO { get; set; }
        public Nullable<System.DateTime> DT_BRASSAGEM { get; set; }
        public Nullable<int> NR_SEMANA_PRODUCAO_INICIO { get; set; }
        public Nullable<int> NR_SEMANA_PRODUCAO_FIM { get; set; }
        public string DS_TANQUE { get; set; }
        public Nullable<bool> FL_UTILIZOU_SAIS { get; set; }
        public Nullable<bool> FL_UTILIZOU_ENZIMAS { get; set; }
        public Nullable<System.DateTime> DT_INICIO_MOAGEM { get; set; }
        public Nullable<System.DateTime> DT_FIM_MOAGEM { get; set; }
        public string DS_ANALISE_MOAGEM { get; set; }
        public Nullable<decimal> NR_DIST_ROLOS_MOAGEM { get; set; }
        public Nullable<decimal> VL_RENDIMENTO_BRASSAGEM { get; set; }
        public Nullable<decimal> VL_PERDA_EXTRATO { get; set; }
        public Nullable<int> ID_PREPARO_AGUA { get; set; }
        public Nullable<int> ID_USUARIO_RESPONSAVEL { get; set; }
        public Nullable<int> ID_REPOUSO { get; set; }
        public Nullable<int> ID_SACARIFICACAO { get; set; }
        public Nullable<int> ID_RENDIMENTO_MOSTURA { get; set; }
        public Nullable<int> ID_CLARIFICACAO { get; set; }
        public Nullable<int> ID_MOSTO_PRIMARIO { get; set; }
        public Nullable<int> ID_TIPO_CERVEJA { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_BRASSAGEM_MOAGEM> TB_BRASSAGEM_MOAGEM { get; set; }
        public virtual TB_CLARIFICACAO TB_CLARIFICACAO { get; set; }
        public virtual TB_MOSTO_PRIMARIO TB_MOSTO_PRIMARIO { get; set; }
        public virtual TB_PREPARO_AGUA TB_PREPARO_AGUA { get; set; }
        public virtual TB_REPOUSO TB_REPOUSO { get; set; }
        public virtual TB_RENDIMENTO_MOSTURA TB_RENDIMENTO_MOSTURA { get; set; }
        public virtual TB_SACARIFICACAO TB_SACARIFICACAO { get; set; }
        public virtual TB_TIPO_CERVEJA TB_TIPO_CERVEJA { get; set; }
        public virtual TB_USUARIO TB_USUARIO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_REGISTRO_LAVAGEM> TB_REGISTRO_LAVAGEM { get; set; }
    }
}
