//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace api_model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_CALDEIRA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_CALDEIRA()
        {
            this.TB_LUPULO = new HashSet<TB_LUPULO>();
        }
    
        public int ID_CALDEIRA { get; set; }
        public Nullable<decimal> VL_VOLUME_CALDEIRA_CHEIA { get; set; }
        public Nullable<decimal> VL_EXTRATO_CALDEIRA_CHEIO { get; set; }
        public Nullable<decimal> VL_PH_INICIAL { get; set; }
        public Nullable<decimal> VL_PH_FINAL { get; set; }
        public Nullable<System.DateTime> HR_INICIO_FERVURA { get; set; }
        public Nullable<System.DateTime> HR_FINAL_FERVURA { get; set; }
        public Nullable<decimal> VL_TOTAL_FERVURA { get; set; }
        public Nullable<decimal> VL_QUANT_ACUCAR { get; set; }
        public Nullable<decimal> VL_TEOR_AMARGOR { get; set; }
        public Nullable<decimal> VL_DOSAGEM_CLEARMAX { get; set; }
        public Nullable<decimal> VL_DOSAGEM_WHIRFLOC { get; set; }
        public Nullable<decimal> VL_RELACAO_DOSAGEM_WHIRFLOC { get; set; }
        public Nullable<decimal> VL_DOSAGEM_SERVOMYCES { get; set; }
        public string DS_ANALISE_FORMACAO_TRUB { get; set; }
        public Nullable<decimal> VL_EXTRATO_APRONTE { get; set; }
        public Nullable<decimal> VL_TAXA_EVAPORACAO { get; set; }
        public Nullable<decimal> VL_PRESSAO_CALDEIRA { get; set; }
        public Nullable<decimal> VL_TEMPO_CIRCULACAO { get; set; }
        public Nullable<System.DateTime> HR_INICIO_REPOUSO { get; set; }
        public Nullable<System.DateTime> HR_FINAL_REPOUSO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_LUPULO> TB_LUPULO { get; set; }
    }
}
