//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace api_model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_CLARIFICACAO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_CLARIFICACAO()
        {
            this.TB_BRASSAGEM = new HashSet<TB_BRASSAGEM>();
        }
    
        public int ID_CLARIFICACAO { get; set; }
        public Nullable<decimal> VL_CARGA_FILTRO { get; set; }
        public Nullable<decimal> VL_VOLUME_LASTRO { get; set; }
        public Nullable<decimal> VL_TEMPO_REPOUSO { get; set; }
        public Nullable<System.DateTime> HR_INICIO_CIRCULACAO { get; set; }
        public Nullable<System.DateTime> HR_FINAL_CIRCULACAO { get; set; }
        public Nullable<decimal> VL_VOLUME_CLARIFICACAO { get; set; }
        public Nullable<decimal> VL_EXTRATO { get; set; }
        public string VL_ANALISE_SOLIDOS { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_BRASSAGEM> TB_BRASSAGEM { get; set; }
    }
}
