//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace api_model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_LUPULO
    {
        public int ID_LUPULO { get; set; }
        public int ID_CALDEIRA { get; set; }
        public int ID_TIPO_LUPULO { get; set; }
        public string DS_LOTE { get; set; }
        public Nullable<decimal> VL_QUANT { get; set; }
        public Nullable<decimal> VL_RENDIMENTO { get; set; }
        public Nullable<System.DateTime> HR_DOSAGEM { get; set; }
    
        public virtual TB_CALDEIRA TB_CALDEIRA { get; set; }
        public virtual TB_TIPO_LUPULO TB_TIPO_LUPULO { get; set; }
    }
}
