//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace api_model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_PREPARO_AGUA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_PREPARO_AGUA()
        {
            this.TB_BRASSAGEM = new HashSet<TB_BRASSAGEM>();
        }
    
        public int ID_PREPARO_AGUA { get; set; }
        public Nullable<decimal> VL_VOLUME_AGUA { get; set; }
        public Nullable<decimal> VL_CLORO { get; set; }
        public Nullable<decimal> VL_TEMP { get; set; }
        public Nullable<decimal> VL_REL_AGUA_MALTE { get; set; }
        public Nullable<decimal> VL_ULTRAFLO_RECOMENDADO { get; set; }
        public Nullable<decimal> VL_ULTRAFLO_UTILIZADO { get; set; }
        public Nullable<decimal> VL_MALTEZYN_UTILIZADO { get; set; }
        public Nullable<decimal> VL_ACIDO_FOSFORICO { get; set; }
        public Nullable<decimal> VL_ACIDO_LATICO { get; set; }
        public Nullable<decimal> VL_SULFATO_CALCIO { get; set; }
        public Nullable<decimal> VL_CLORETO_CALCIO { get; set; }
        public Nullable<decimal> VL_PH { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_BRASSAGEM> TB_BRASSAGEM { get; set; }
    }
}
