//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace api_model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_RENDIMENTO_MOSTURA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_RENDIMENTO_MOSTURA()
        {
            this.TB_BRASSAGEM = new HashSet<TB_BRASSAGEM>();
        }
    
        public int ID_RENDIMENTO_MOSTURA { get; set; }
        public Nullable<decimal> VL_EXTRATO_FINAL_MOSTURA { get; set; }
        public Nullable<decimal> VL_DENSIDADE_MOSTURA { get; set; }
        public Nullable<decimal> VL_EXTRATO_TEORICO_MOSTURA { get; set; }
        public Nullable<decimal> VL_EXTRATO_REAL_MOSTURA { get; set; }
        public Nullable<decimal> VL_RENDIMENTO_MOSTURA { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_BRASSAGEM> TB_BRASSAGEM { get; set; }
    }
}
