//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace api_model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_SACARIFICACAO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_SACARIFICACAO()
        {
            this.TB_BRASSAGEM = new HashSet<TB_BRASSAGEM>();
        }
    
        public int ID_SACARIFICACAO { get; set; }
        public Nullable<decimal> VL_TEMP_SACARIFICACAO { get; set; }
        public Nullable<System.DateTime> DT_HORA_INICIO_SACARIFICACAO { get; set; }
        public Nullable<System.DateTime> DT_HORA_FIM_SACARIFICACAO { get; set; }
        public string VL_TESTE_IODO_SACARIFICACAO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_BRASSAGEM> TB_BRASSAGEM { get; set; }
    }
}
