//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace api_model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_USUARIO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_USUARIO()
        {
            this.TB_BRASSAGEM = new HashSet<TB_BRASSAGEM>();
        }
    
        public int ID_USUARIO { get; set; }
        public string DS_NOME { get; set; }
        public string DS_EMAIL { get; set; }
        public string DS_LOGIN { get; set; }
        public string DS_SENHA { get; set; }
        public int NR_DDD { get; set; }
        public int NR_TELEFONE { get; set; }
        public string DS_FUNCAO { get; set; }
        public bool FL_ADMINISTRADOR { get; set; }
        public bool FL_REMEMBER { get; set; }
        public int ID_EMPRESA { get; set; }
        public string DS_TOKEN_EMPRESA { get; set; }
        public bool FL_EMPRESA { get; set; }
        public string DS_TOKEN_RECOVERY { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_BRASSAGEM> TB_BRASSAGEM { get; set; }
        public virtual TB_EMPRESA TB_EMPRESA { get; set; }
    }
}
